// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Запись: слот, закреплённый за гостем.
 */
export type Booking = {
    id: string;
    slotId: string;
    /**
     * Имя гостя — обязательно
     */
    guestName: string;
    /**
     * Email гостя — обязательно
     */
    guestEmail: string;
    createdAt: string;
};

/**
 * Тип встречи: разновидность встречи, которую задаёт владелец (название, описание, длительность).
 */
export type EventType = {
    id: string;
    title: string;
    /**
     * Описание типа встречи
     */
    description?: string;
    /**
     * Длительность в минутах; определяет длительность слотов этого типа
     */
    durationMinutes: number;
};

/**
 * Слот: свободный интервал, опубликованный владельцем; длительность определяется типом встречи.
 */
export type Slot = {
    id: string;
    /**
     * Тип встречи, к которому относится слот
     */
    eventTypeId: string;
    startDateTime: string;
    endDateTime: string;
};

/**
 * Предстоящая встреча: ракурс владельца — запись со временем слота и типом встречи.
 */
export type UpcomingMeeting = {
    id: string;
    slotId: string;
    guestName: string;
    guestEmail: string;
    startDateTime: string;
    endDateTime: string;
    eventTypeId: string;
    eventTitle: string;
};

export type BookingsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bookings';
};

export type BookingsListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Booking>;
};

export type BookingsListResponse = BookingsListResponses[keyof BookingsListResponses];

export type BookingsCreateData = {
    body: Booking;
    path?: never;
    query?: never;
    url: '/bookings';
};

export type BookingsCreateErrors = {
    /**
     * Невалидный ввод: обязательные поля пусты или значения вне допустимых границ.
     */
    400: unknown;
    /**
     * Слот или тип встречи не найдены.
     */
    404: unknown;
    /**
     * Слот уже занят: на слот не может быть более одной записи.
     */
    409: unknown;
};

export type BookingsCreateResponses = {
    /**
     * The request has succeeded.
     */
    200: Booking;
};

export type BookingsCreateResponse = BookingsCreateResponses[keyof BookingsCreateResponses];

export type EventTypesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/event-types';
};

export type EventTypesListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<EventType>;
};

export type EventTypesListResponse = EventTypesListResponses[keyof EventTypesListResponses];

export type EventTypesCreateData = {
    body: EventType;
    path?: never;
    query?: never;
    url: '/event-types';
};

export type EventTypesCreateErrors = {
    /**
     * Невалидный ввод: обязательные поля пусты или значения вне допустимых границ.
     */
    400: unknown;
};

export type EventTypesCreateResponses = {
    /**
     * The request has succeeded.
     */
    200: EventType;
};

export type EventTypesCreateResponse = EventTypesCreateResponses[keyof EventTypesCreateResponses];

export type SlotsListData = {
    body?: never;
    path?: never;
    query?: {
        eventTypeId?: string;
    };
    url: '/slots';
};

export type SlotsListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Slot>;
};

export type SlotsListResponse = SlotsListResponses[keyof SlotsListResponses];

export type SlotsCreateData = {
    body: Slot;
    path?: never;
    query?: never;
    url: '/slots';
};

export type SlotsCreateErrors = {
    /**
     * Невалидный ввод: обязательные поля пусты или значения вне допустимых границ.
     */
    400: unknown;
    /**
     * Слот или тип встречи не найдены.
     */
    404: unknown;
};

export type SlotsCreateResponses = {
    /**
     * The request has succeeded.
     */
    200: Slot;
};

export type SlotsCreateResponse = SlotsCreateResponses[keyof SlotsCreateResponses];

export type UpcomingMeetingsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/upcoming-meetings';
};

export type UpcomingMeetingsListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<UpcomingMeeting>;
};

export type UpcomingMeetingsListResponse = UpcomingMeetingsListResponses[keyof UpcomingMeetingsListResponses];
