// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Запись: слот, закреплённый за гостем.
 */
export type Booking = {
    id: string;
    slotId: string;
    /**
     * Имя гостя — обязательно
     */
    guestName: string;
    /**
     * Email гостя — обязательно
     */
    guestEmail: string;
    createdAt: string;
};

/**
 * Тип встречи: разновидность встречи, которую задаёт владелец (название, описание, длительность).
 */
export type EventType = {
    id: string;
    title: string;
    /**
     * Описание типа встречи
     */
    description?: string;
    /**
     * Длительность в минутах; определяет длительность слотов этого типа
     */
    durationMinutes: number;
};

/**
 * Запрос переноса записи: новый свободный слот того же типа встречи.
 */
export type RescheduleRequest = {
    /**
     * Новый слот — свободный, того же типа встречи
     */
    newSlotId: string;
};

/**
 * Слот: свободный интервал, опубликованный владельцем; длительность определяется типом встречи.
 */
export type Slot = {
    id: string;
    /**
     * Тип встречи, к которому относится слот
     */
    eventTypeId: string;
    startDateTime: string;
    endDateTime: string;
};

/**
 * Предстоящая встреча: ракурс владельца — запись со временем слота и типом встречи.
 */
export type UpcomingMeeting = {
    id: string;
    slotId: string;
    guestName: string;
    guestEmail: string;
    startDateTime: string;
    endDateTime: string;
    eventTypeId: string;
    eventTitle: string;
};

/**
 * Рабочие часы владельца: IANA-зона и набор правил окон; расписание одно на владельца.
 */
export type WorkingHours = {
    /**
     * IANA-имя часовой зоны владельца, например «Europe/Moscow»
     */
    timeZone: string;
    /**
     * Правила окон; пустой массив выключает рабочие окна
     */
    rules: Array<WorkingHoursRule>;
};

/**
 * Правило рабочего окна: дни недели и интервал настенного времени в пределах одних суток.
 */
export type WorkingHoursRule = {
    /**
     * Дни недели в ISO-нумерации: 1 — понедельник … 7 — воскресенье
     */
    weekdays: Array<number>;
    /**
     * Начало окна, «HH:MM», на 30-минутной сетке
     */
    startTime: string;
    /**
     * Конец окна, «HH:MM», на 30-минутной сетке; позже начала, в пределах суток
     */
    endTime: string;
};

export type BookingsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/bookings';
};

export type BookingsListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Booking>;
};

export type BookingsListResponse = BookingsListResponses[keyof BookingsListResponses];

export type BookingsCreateData = {
    body: Booking;
    path?: never;
    query?: never;
    url: '/bookings';
};

export type BookingsCreateErrors = {
    /**
     * Невалидный ввод: обязательные поля пусты или значения вне допустимых границ.
     */
    400: unknown;
    /**
     * Запись, слот или тип встречи не найдены.
     */
    404: unknown;
    /**
     * Конфликт: интервал времени уже занят, либо тип встречи/слот с таким же содержимым уже существуют — повторные отправки формы и сетевые повторы не создают дубликатов.
     */
    409: unknown;
};

export type BookingsCreateResponses = {
    /**
     * The request has succeeded.
     */
    200: Booking;
};

export type BookingsCreateResponse = BookingsCreateResponses[keyof BookingsCreateResponses];

export type BookingsCancelData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/bookings/{id}';
};

export type BookingsCancelErrors = {
    /**
     * Запись, слот или тип встречи не найдены.
     */
    404: unknown;
};

export type BookingsCancelResponses = {
    /**
     * There is no content to send for this request, but the headers may be useful.
     */
    204: void;
};

export type BookingsCancelResponse = BookingsCancelResponses[keyof BookingsCancelResponses];

export type BookingsRescheduleData = {
    body: RescheduleRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/bookings/{id}/reschedule';
};

export type BookingsRescheduleErrors = {
    /**
     * Невалидный ввод: обязательные поля пусты или значения вне допустимых границ.
     */
    400: unknown;
    /**
     * Запись, слот или тип встречи не найдены.
     */
    404: unknown;
    /**
     * Конфликт: интервал времени уже занят, либо тип встречи/слот с таким же содержимым уже существуют — повторные отправки формы и сетевые повторы не создают дубликатов.
     */
    409: unknown;
};

export type BookingsRescheduleResponses = {
    /**
     * The request has succeeded.
     */
    200: Booking;
};

export type BookingsRescheduleResponse = BookingsRescheduleResponses[keyof BookingsRescheduleResponses];

export type EventTypesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/event-types';
};

export type EventTypesListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<EventType>;
};

export type EventTypesListResponse = EventTypesListResponses[keyof EventTypesListResponses];

export type EventTypesCreateData = {
    body: EventType;
    path?: never;
    query?: never;
    url: '/event-types';
};

export type EventTypesCreateErrors = {
    /**
     * Невалидный ввод: обязательные поля пусты или значения вне допустимых границ.
     */
    400: unknown;
    /**
     * Конфликт: интервал времени уже занят, либо тип встречи/слот с таким же содержимым уже существуют — повторные отправки формы и сетевые повторы не создают дубликатов.
     */
    409: unknown;
};

export type EventTypesCreateResponses = {
    /**
     * The request has succeeded.
     */
    200: EventType;
};

export type EventTypesCreateResponse = EventTypesCreateResponses[keyof EventTypesCreateResponses];

export type SlotsListData = {
    body?: never;
    path?: never;
    query?: {
        eventTypeId?: string;
    };
    url: '/slots';
};

export type SlotsListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<Slot>;
};

export type SlotsListResponse = SlotsListResponses[keyof SlotsListResponses];

export type SlotsCreateData = {
    body: Slot;
    path?: never;
    query?: never;
    url: '/slots';
};

export type SlotsCreateErrors = {
    /**
     * Невалидный ввод: обязательные поля пусты или значения вне допустимых границ.
     */
    400: unknown;
    /**
     * Запись, слот или тип встречи не найдены.
     */
    404: unknown;
    /**
     * Конфликт: интервал времени уже занят, либо тип встречи/слот с таким же содержимым уже существуют — повторные отправки формы и сетевые повторы не создают дубликатов.
     */
    409: unknown;
};

export type SlotsCreateResponses = {
    /**
     * The request has succeeded.
     */
    200: Slot;
};

export type SlotsCreateResponse = SlotsCreateResponses[keyof SlotsCreateResponses];

export type UpcomingMeetingsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/upcoming-meetings';
};

export type UpcomingMeetingsListResponses = {
    /**
     * The request has succeeded.
     */
    200: Array<UpcomingMeeting>;
};

export type UpcomingMeetingsListResponse = UpcomingMeetingsListResponses[keyof UpcomingMeetingsListResponses];

export type WorkingHoursApiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/working-hours';
};

export type WorkingHoursApiGetResponses = {
    /**
     * The request has succeeded.
     */
    200: WorkingHours;
};

export type WorkingHoursApiGetResponse = WorkingHoursApiGetResponses[keyof WorkingHoursApiGetResponses];

export type WorkingHoursApiReplaceData = {
    body: WorkingHours;
    path?: never;
    query?: never;
    url: '/working-hours';
};

export type WorkingHoursApiReplaceErrors = {
    /**
     * Невалидный ввод: обязательные поля пусты или значения вне допустимых границ.
     */
    400: unknown;
};

export type WorkingHoursApiReplaceResponses = {
    /**
     * The request has succeeded.
     */
    200: WorkingHours;
};

export type WorkingHoursApiReplaceResponse = WorkingHoursApiReplaceResponses[keyof WorkingHoursApiReplaceResponses];
